apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
            ephemeral-storage: 1Gi
          limits:
            memory: 256Mi
            cpu: 200m
            ephemeral-storage: 2Gi
        image: consumer
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-consumer
spec:
  rules:
  - host: consumer.kulvetal.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: consumer
            port:
              number: 80
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-consumer-new
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
#spec:
#  rules:
#  - host: api-redfdev.cvlabs.net
#    http:
#      paths:
#      - path: /conf-api(/|$)(.*)
#        pathType: Prefix
#        backend:
#          service:
#            name: consumer
#            port:
#              number: 80
