name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Sandbox/TelegramBot/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Sandbox/TelegramBot/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build Sandbox/TelegramBot --file Sandbox/TelegramBot/src/TelegramBot/Dockerfile --tag trash-recycling-bot:$(date +%s)
      
    - name: Log into GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/trash-recycling-bot:${{ github.run_id }}
